PRINT_VERBOSITY = "high"
EXCLUDED_DIRS = [".DS_Store"]
TEMPDIR = "/tmp"
TEXTTABLE_STYLE = ["-", "|", "+", "-"]
MINIMUM_PYTHON_VERSION = (3, 6, 0)
PRINT_VERBOSITY = "high"
EXCLUDED_DIRS = [".DS_Store"]
TEXTTABLE_STYLE = ["-", "|", "+", "-"]
MINIMUM_PYTHON_VERSION = (3, 6, 0)
socket_host = "0.0.0.0"
POSTGRES_URL = "none"
POSTGRES_USER = "none"
POSTGRES_PW = "none"
POSTGRES_DB = "none"
UPLOAD_FOLDER = "uploads"
ALLOWED_EXTENSIONS = ["txt", "pdf", "png", "jpg", "jpeg", "gif", "zip"]
TEXTTABLE_STYLE = ["-", "|", "+", "-"]
SERVER_PORT = 5000
SERVER_HOST = "0.0.0.0"
